name: Build VSIX

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Install dependencies
      run: npm install
      
    - name: Install vsce
      run: npm install -g vsce
      
    - name: Build VSIX
      run: vsce package
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: extension
        path: '*.vsix'